macho(abraham).
macho(homero).
macho(clancy).
macho(mrburns).
macho(skinner).
macho(bart).
macho(milhouse).
macho(snowball).
macho(helper).
hembra(mirna).
hembra(marge).
hembra(jacquelin).
hembra(paty).
hembra(selma).
hembra(lisa).
hembra(maggie).
hembra(edna).

macho(abraham,homero).